"""added new model

Revision ID: bd7be64bffe8
Revises: 
Create Date: 2023-07-20 09:52:51.940345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7be64bffe8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('url_map', 'short',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_index('ix_url_map_timestamp', table_name='url_map')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_url_map_timestamp', 'url_map', ['timestamp'], unique=False)
    op.alter_column('url_map', 'short',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
